api:
  host: 0.0.0.0
  port: 8080
chains:
  waves:
    chain_id: 84
    base_url: https://nodes-testnet.wavesnodes.com
    supported_asset_ids:
      - BrmjyAWT5jjr3Wpsiyivyvg5vDuzoX2s93WgiexXetB3
  ethereum:
    chain_id: '0x3'
    base_url: https://ropsten.infura.io/v3/54d695ba95014f49985ba18c0a97205f
    supported_asset_ids:
      - '0x6EE856Ae55B6E1A249f04cd3b947141bc146273c'
      - '0xFE724a829fdF12F7012365dB98730EEe33742ea2'
    multicall_contract_address: '0x53C43764255c17BD724F74c4eF150724AC50a3ed'
